/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "print_request.h"

bool_t
xdr_Tupla (XDR *xdrs, Tupla *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->username, 256))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->operation, 20))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->filename, 256))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->time, 20))
		 return FALSE;
	return TRUE;
}
