/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_REQUEST_H_RPCGEN
#define _PRINT_REQUEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Tupla {
	char username[256];
	char operation[20];
	char filename[256];
	char time[20];
};
typedef struct Tupla Tupla;

#define PRINT_REQUEST_PROG 0x20000001
#define PRINT_REQUEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_REQUEST 1
extern  void * print_request_1(Tupla *, CLIENT *);
extern  void * print_request_1_svc(Tupla *, struct svc_req *);
extern int print_request_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_REQUEST 1
extern  void * print_request_1();
extern  void * print_request_1_svc();
extern int print_request_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Tupla (XDR *, Tupla*);

#else /* K&R C */
extern bool_t xdr_Tupla ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_REQUEST_H_RPCGEN */
